import Link from "next/link";
import { getLatestNews } from "@/lib/data/news";
import type { NewsItem } from "@/lib/schemas/newsSchema";
import HeroCarousel from "@/components/home/HeroCarousel";

const DESCRIPTION_WORD_LIMIT = 60;

const INTRO_PARAGRAPHS = [
  "The Language Understanding and Representation (LUNAR) Lab investigates how language is understood, represented, and generated by humans and machines alike. Our work sits at the intersection of natural language processing, cognitive science, machine learning, and interpretability. We study both the capabilities and limitations of modern AI systems, asking not only whether models can perform a task, but also what kinds of representations, mechanisms, and assumptions support their behavior.",
  "A central goal of the lab is to build a deeper scientific understanding of language and cognition through computational models. We use neural networks as objects of study, experimental tools, and theoretical probes. By comparing artificial systems with human reasoning, perception, and communication, we aim to better understand what it means for a system to represent meaning, learn concepts, follow structure, and generalize beyond surface-level patterns.",
];

const RESEARCH_AREAS = [
  {
    title: "Understanding Neural Networks Under the Hood",
    description:
      "We study the internal mechanisms of neural networks to understand why they behave the way they do. This includes work on interpretability, circuit analysis, probing, model representations, factual recall, and the structure of learned concepts. Rather than treating neural models as black boxes, we investigate the components and computations that give rise to their behavior.",
  },
  {
    title: "Connecting Language to the Non-Linguistic World",
    description:
      "Language is not only a symbolic system. It is connected to perception, action, physical environments, and social interaction. Our research explores grounding, embodied AI, vision-language models, affordance learning, and the relationship between linguistic meaning and real-world experience. We ask how models can connect words to what people see, do, and understand in the world.",
  },
  {
    title: "Relating Natural and Artificial Intelligence",
    description:
      "We use computational models to ask questions about human cognition and learning. This work connects neural networks with theories from psychology, cognitive science, and linguistics. By studying how artificial systems learn concepts, relations, logic, and abstractions, we aim to understand both the promise and the limits of using AI systems as models of human thought.",
  },
  {
    title: "NLP and Society",
    description:
      "Language technologies shape how people communicate, search for information, and interact with institutions. Our work examines the social dimensions of NLP, including bias, fairness, connotation, formality, affect, and human disagreement. We study how language models reflect, amplify, or transform social meanings, and how evaluation methods can better capture these effects.",
  },
];

function truncateWords(text: string, limit: number): string {
  const words = text.trim().split(/\s+/);
  if (words.length <= limit) return text;
  return words.slice(0, limit).join(" ") + "…";
}

// Format ISO date string → { month: "JANUARY", year: "2025" }
function formatDate(dateStr: string) {
  const d = new Date(dateStr + "T00:00:00");
  return {
    month: d.toLocaleString("en-US", { month: "long" }).toUpperCase(),
    year: d.getFullYear().toString(),
  };
}


// Chevron-right arrow — exact path from Figma, color via CSS variable
function ChevronRight({ color }: { color: string }) {
  return (
    <svg width="25" height="46" viewBox="0 0 25 46" fill="none">
      <path
        d="M1.09339e-05 3.7343L3.66938 5.74025e-06L23.6555 20.3519C23.9777 20.678 24.2334 21.0658 24.4078 21.493C24.5823 21.9201 24.6721 22.3782 24.6721 22.8409C24.6721 23.3035 24.5823 23.7616 24.4078 24.1888C24.2334 24.6159 23.9777 25.0037 23.6555 25.3298L3.66937 45.6923L0.00346247 41.958L18.7619 22.8462L1.09339e-05 3.7343Z"
        fill={color}
      />
    </svg>
  );
}

function SectionDivider({ marginTop = 8 }: { marginTop?: number }) {
  return (
    <div
      style={{
        width: "100%",
        height: 0,
        outline: "1px solid var(--foreground)",
        outlineOffset: -0.5,
        marginTop,
      }}
    />
  );
}

function ResearchAreaCard({
  title,
  description,
  index,
}: {
  title: string;
  description: string;
  index: number;
}) {
  return (
    <article
      style={{
        minHeight: 310,
        border: "1px solid var(--foreground)",
        padding: "30px 32px 34px",
        color: "var(--foreground)",
        background: "var(--background)",
      }}
    >
      <div
        style={{
          fontFamily: "'Be Vietnam Pro', sans-serif",
          fontSize: 14,
          lineHeight: "18px",
          marginBottom: 26,
          color: "var(--foreground)",
        }}
      >
        0{index + 1}
      </div>
      <h3
        className="text-[34px] leading-[36px] md:text-[42px] md:leading-[42px]"
        style={{
          fontFamily: "'FreightText Pro', serif",
          fontStyle: "italic",
          fontWeight: 400,
          color: "var(--foreground)",
          margin: "0 0 22px",
          overflowWrap: "break-word",
        }}
      >
        {title}
      </h3>
      <p
        style={{
          fontFamily: "'Be Vietnam Pro', sans-serif",
          fontWeight: 400,
          fontSize: 18,
          lineHeight: "28px",
          color: "var(--foreground)",
          margin: 0,
        }}
      >
        {description}
      </p>
    </article>
  );
}

function NewsRow({ item }: { item: NewsItem }) {
  const { month, year } = formatDate(item.date);
  return (
    <div>
      {/* Row: date | title+description | image */}
      <div
        className="grid grid-cols-1 gap-5 py-8 md:grid-cols-[108px_minmax(0,1fr)_220px] md:gap-8 md:py-10 lg:grid-cols-[108px_minmax(0,1fr)_274px]"
        style={{
          color: "var(--foreground)",
        }}
      >
        {/* Date */}
        <div
          style={{
            fontFamily: "'Be Vietnam Pro', sans-serif",
            fontWeight: 400,
            fontSize: 14,
            lineHeight: "18px",
            color: "var(--foreground)",
            paddingTop: 8,
          }}
        >
          {month}
          <br />
          {year}
        </div>

        {/* Title + description — links to /blog/[id] */}
        <Link
          href={`/blog/${item.id}`}
          style={{ textDecoration: "none", color: "var(--foreground)", display: "block" }}
        >
          <div
            className="text-[34px] leading-[36px] md:text-[50px] md:leading-[49px]"
            style={{
              fontFamily: "'FreightText Pro', serif",
              fontStyle: "italic",
              fontWeight: 400,
              color: "var(--foreground)",
              marginBottom: 16,
              overflowWrap: "break-word",
            }}
          >
            {item.title}
          </div>
          <div
            style={{
              fontFamily: "'Be Vietnam Pro', sans-serif",
              fontWeight: 400,
              fontSize: 19,
              lineHeight: "28px",
              color: "var(--foreground)",
            }}
          >
            {truncateWords(item.description, DESCRIPTION_WORD_LIMIT)}
          </div>
        </Link>

        {/* Image placeholder */}
        <div
          className="h-[172px] w-full md:w-[220px] lg:w-[274px]"
          style={{
            background: "#D9D9D9",
            flexShrink: 0,
          }}
        />
      </div>

      {/* Divider */}
      <SectionDivider marginTop={0} />
    </div>
  );
}

export default async function HomePage() {
  const newsItems = getLatestNews(3);

  return (
    <main className="box-border w-full overflow-hidden px-5 pt-8 md:px-[60px] lg:px-[125px] lg:pt-[46px]">

      {/* Hero title */}
      <h1
        className="text-[44px] leading-[44px] sm:text-[56px] sm:leading-[54px] md:text-[76px] md:leading-[72px] lg:text-[100px] lg:leading-[90px]"
        style={{
          maxWidth: 989,
          marginBottom: 0,
          overflowWrap: "break-word",
        }}
      >
        Language Understanding and <br className="hidden md:block" />Representation Lab
      </h1>

      <HeroCarousel />

      {/* Introduction */}
      <section className="mt-14 mb-20 w-full max-w-[1243px] md:mt-16 md:mb-24">
        <h2 className="text-[48px] leading-[54px] md:text-[70px] md:leading-[78px]" style={{ margin: 0 }}>
          Introduction
        </h2>
        <SectionDivider />
        <div className="grid gap-8 pt-8 lg:grid-cols-2 lg:gap-12">
          {INTRO_PARAGRAPHS.map((paragraph) => (
            <p
              key={paragraph}
              style={{
                fontFamily: "'Be Vietnam Pro', sans-serif",
                fontWeight: 400,
                fontSize: 19,
                lineHeight: "30px",
                color: "var(--foreground)",
                margin: 0,
              }}
            >
              {paragraph}
            </p>
          ))}
        </div>
      </section>

      {/* Current Research Areas */}
      <section className="mb-24 w-full max-w-[1271px] md:mb-28">
        <h2 className="text-[48px] leading-[54px] md:text-[70px] md:leading-[78px]" style={{ margin: 0 }}>
          Current Research Areas
        </h2>
        <SectionDivider />
        <div className="grid grid-cols-1 gap-5 pt-8 md:grid-cols-2 md:gap-6 md:pt-10">
          {RESEARCH_AREAS.map((area, index) => (
            <ResearchAreaCard
              key={area.title}
              title={area.title}
              description={area.description}
              index={index}
            />
          ))}
        </div>
      </section>

      {/* Recent News */}
      <section className="mb-20 w-full max-w-[1271px]">

        {/* Section header: "Recent News" + chevron */}
        <div style={{ display: "flex", alignItems: "flex-end", gap: 16, marginBottom: 0 }}>
          <h2 className="text-[48px] leading-[54px] md:text-[70px] md:leading-[78px]" style={{ margin: 0 }}>
            Recent News
          </h2>
          <div style={{ paddingBottom: 14, color: "var(--foreground)" }}>
            <ChevronRight color="var(--foreground)" />
          </div>
        </div>

        {/* Top divider */}
        <SectionDivider />

        {/* News rows */}
        {newsItems.map((item) => (
          <NewsRow key={item.id} item={item} />
        ))}
      </section>

    </main>
  );
}
